apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../../base
images:
  - name: ghcr.io/whtbl3/my-app
    newTag: "a1e991b3162354eba7f8c1fc8ed4547feea23b8c"