apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../../base
images:
  - name: ghcr.io/whtbl3/github-action-argocd-app   # ← khớp với base
    newTag: "latest"                                  # ← CI sẽ thay dòng này