apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../../base
images:
  - name: ghcr.io/whtbl3/my-app
    newTag: "91e975f64547384f9e4c4c658cc78a4e7622fb37"