apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production       # ← khác staging

resources:
  - ../../base

images:
  - name: ghcr.io/whtbl3/my-app
    newTag: "1.0.0"         # ← chỉ update khi có release chủ đích

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3            # ← production cần 3 replicas
    target:
      kind: Deployment
      name: my-app